### PR TITLE
Fix/flag icons

### PR DESCRIPTION
**Pull request by MalvinJay**
Changed country icons

### CODE REVIEW

**Comment by rocktimsaikia** [comment]
What is the issue with flags coming from the API?

**Comment by rocktimsaikia** [comment]
I have refactored a bit including this too in the latest commit

**Comment by MalvinJay** [comment]
> What is the issue with flags coming from the API?

Restcountries' flags API wasn't working. I had to change it to flagcdn.com Apparently, they are now using flagcdn

**Comment by MalvinJay** [comment]
> I have refactored a bit including this too in the latest commit

Ohk

**Pull request closed without merging**
